name: CI/CD Pipeline
on:
  push:
    branches: [ runner ]

permissions:
  id-token: write
  contents: read #This is required for actions/checkout@v2

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: directory contents
        run: ls -la

      - name: dir location
        run: pwd
