name: CI/CD Pipeline
on:
  push:
    branches: [ runner ]

permissions:
  id-token: write
  contents: read #This is required for actions/checkout@v2

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: directory contents
        run: ls -la

      - name: dir location
        run: pwd

      - name: install dep
        run: npm install

#      - name: build node app
#        run: npm run build
#
#      - name: move moduels and build folder to prod
#        run: mv build/* /home/ec2-user/prod && mv node_modules/* /home/ec2-user/prod
      - name: change user to root
        run: sudo -i -u ec2-user || echo "already root"

      - name: stop pm2 process
        run: pm2 kill

      - name: clear prod folder
        run: rm -rf /home/ec2-user/prod/*

      - name: move files to prod folder
        run: mv * /home/ec2-user/prod

      - name: go to prod folder
        run: cd /home/ec2-user/prod && ls

      - name: start app
        run: cd /home/ec2-user/prod && sudo pm2 start app.js --name "runner-app" && pm2 save
