name: CI/CD Pipeline
on:
  push:
    branches: [ runner ]

permissions:
  id-token: write
  contents: read #This is required for actions/checkout@v2

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: directory contents
        run: ls -la

      - name: dir location
        run: pwd

      - name: install dep
        run: npm install

      - name: build node app
        run: npm run build

      - name: move moduels and build folder to prod
        run: mv build/* /home/ec2-user/prod && mv node_modules/* /home/ec2-user/prod

      - name: go to prod folder
        run: cd /home/ec2-user/prod

      - name: start app using pm2
        run: pm2 start build/index.js --name "sockets" -- start && pm2 save
